
spring.datasource.jndi-name=java:/comp/env/jdbc/sakila

# Opcional: posar el context-path si vols
# server.servlet.context-path=/botiga


# Nom del perfil
spring.profiles.default=prod
logging.path=/opt/tomcat/logs/sakila