app.datasource.jndi-name=java:/comp/env/jdbc/sakila

# Opcional: posar el context-path si vols
# server.servlet.context-path=/botiga

spring.datasource.url=jdbc:mysql://localhost:3306/sakila?serverTimezone=UTC&useSSL=false
spring.datasource.username=userSakila
spring.datasource.password=Prova1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Nom del perfil
logging.path=./logs/sakila