ServerName localhost

# Carregar mòduls necessaris
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
LoadModule headers_module modules/mod_headers.so
LoadModule slotmem_shm_module modules/mod_slotmem_shm.so

# Logs a stdout (Docker-friendly)
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common

# Activar proxy
ProxyRequests Off
ProxyPreserveHost On

# Definir el balancer
<Proxy "balancer://tomcat-cluster">
    BalancerMember "http://tomcat1:8080" route=tomcat1
    BalancerMember "http://tomcat2:8080" route=tomcat2
    ProxySet lbmethod=byrequests
    ProxySet stickysession=JSESSIONID|jsessionid
</Proxy>

ProxyPass "/balancer-manager" !

# Redirigir tot el tràfic cap al balancer
ProxyPass "/" "balancer://tomcat-cluster/"
ProxyPassReverse "/" "balancer://tomcat-cluster/"

<Location "/balancer-manager">
    SetHandler balancer-manager
    Require all granted
</Location>
